version: '3.9'

services:
  etiqa_be:
    container_name: etiqa_be
    image: etiqa_be
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - SQL_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    extra_hosts:
      - "mysql:127.0.0.1"
    
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --pid-file=/var/run/mysqld/mysqld.pid
    environment:
      - MYSQL_ROOT_PASSWORD=devguy123
      - MYSQL_DATABASE=etiqadb
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3